apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: shreyans25/host-spring
	env:
          - name: python-api-url
            value: "http://python-svc"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: ingress-nginx
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring

